# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt_Gui\Snake_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 531)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.push_button_join = QtWidgets.QPushButton(self.centralwidget)
        self.push_button_join.setObjectName("push_button_join")
        self.horizontalLayout.addWidget(self.push_button_join)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.widget_open_game = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_open_game.sizePolicy().hasHeightForWidth())
        self.widget_open_game.setSizePolicy(sizePolicy)
        self.widget_open_game.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_open_game.setObjectName("widget_open_game")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget_open_game)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 830, 30))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grid_layout_open_game = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grid_layout_open_game.setContentsMargins(0, 0, 0, 0)
        self.grid_layout_open_game.setObjectName("grid_layout_open_game")
        self.line_edit_open_game = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.line_edit_open_game.setObjectName("line_edit_open_game")
        self.grid_layout_open_game.addWidget(self.line_edit_open_game, 1, 1, 1, 1)
        self.label_open_game = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_open_game.setObjectName("label_open_game")
        self.grid_layout_open_game.addWidget(self.label_open_game, 1, 0, 1, 1)
        self.push_button_open_game = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.push_button_open_game.setObjectName("push_button_open_game")
        self.grid_layout_open_game.addWidget(self.push_button_open_game, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_open_game)
        self.widget_join_game = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_join_game.sizePolicy().hasHeightForWidth())
        self.widget_join_game.setSizePolicy(sizePolicy)
        self.widget_join_game.setMinimumSize(QtCore.QSize(0, 230))
        self.widget_join_game.setObjectName("widget_join_game")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget_join_game)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 830, 229))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_layout_join_game = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_layout_join_game.setContentsMargins(0, 0, 0, 0)
        self.grid_layout_join_game.setObjectName("grid_layout_join_game")
        self.open_games_table = QtWidgets.QTableView(self.gridLayoutWidget)
        self.open_games_table.setObjectName("open_games_table")
        self.grid_layout_join_game.addWidget(self.open_games_table, 1, 0, 1, 1)
        self.push_button_join_game = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.push_button_join_game.setObjectName("push_button_join_game")
        self.grid_layout_join_game.addWidget(self.push_button_join_game, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_join_game)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Snake"))
        self.pushButton_2.setText(_translate("MainWindow", "Open Game"))
        self.pushButton.setText(_translate("MainWindow", "Start Server"))
        self.push_button_join.setText(_translate("MainWindow", "Show open games"))
        self.label_open_game.setText(_translate("MainWindow", "Game Name"))
        self.push_button_open_game.setText(_translate("MainWindow", "Open Game"))
        self.push_button_join_game.setText(_translate("MainWindow", "Join Game"))

